import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../lib/Providers";
import { AppBar } from "@/features/app-bar/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="w-screen flex flex-column bg-primary text-primary-foreground">
            <div className="min-h-screen w-max flex-auto overflow-auto flex flex-col">
              <AppBar />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
